name: Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy to GitHub Pages
        run: |
          git checkout -B gh-pages
          git add -f storybook-static
          git commit -m "Deploy Storybook to GitHub Pages"
          git push -f origin gh-pages

      - name: Cleanup
        run: |
          git checkout main
          git branch -D gh-pages
