name: Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: yarn

      - name: Build Storybook
        run: yarn build-storybook
