name: Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: yarn

      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          path: storybook-static
          build_command: yarn build-storybook
