name: Publish Storybook to GitHub Pages

on:
  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout code
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install Dependencies
        run: yarn

      - name: Build Storybook
        run: yarn build-storybook

      # - name: Authenticate with the GitHub Package Registry
      #   run:
      #     echo "//npm.pkg.github.com:_authToken=${{ secrets.SECRET_GITHUB_TOKEN }}" >
      #     ~/.npmrc

      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/henriqueidt/poc-storybook-7
          git config --global user.name "Henrique Eidt"
          git config --global user.email "henriqueidt@gmail.com"
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initializing gh-pages branch"
          git checkout main
          git checkout gh-pages
          mkdir ${{ steps.extract_branch.outputs.branch }}
          cd storybook-static
          mv * ../${{ steps.extract_branch.outputs.branch }}
          cd ..
          git add -f ${{ steps.extract_branch.outputs.branch }}
          git commit -m "Deploy Storybook to GitHub Pages"
          git push -f origin gh-pages

      - name: Cleanup
        run: |
          git checkout main
          git branch -D gh-pages
